//editable

let hearts = 10;
let score = 0;
let enemiesInWave = 5;
let enemiesSpawn = 0;
let enemixInCurrentWave = 0;
let enemyIncrease = 1;
let damageProjectiles = 10;
let radiusBuildings = 250;
let speedProjectiles = 30;
let speedSlowProjectiles = 3;

let fireRate = 45;
let attackTowerPrice = 50;
let slowTowerPrice = 50;
let coinsPerAttack = 0.05;
let coins = 50;

//difficulty :
let initSpeedEnemies = 1;
let speedEnemies = initSpeedEnemies;

// init

frozen = false;
let gameOver = false;
let pause = false;
let rightkey = false;
let slowTowerOccupied = false;
let wave = 0;
let round = 0;
let waveEnded = true;
let index = 0;
let explosionsEnemy = [];
let explosionsPlayerHit = [];
let explosionsGameOver = [];
let frozenEnemies = [];
let slowProjectiles = [];
let placementTiles = [];
let buildings = [];
let players = [];
let enemies = [];
let usedWords = [];
let projectiles = [];
let activeTile = undefined;
let selectedTarget = null;
let isSelected = false;
let mouse = {
  x: undefined,
  y: undefined,
};
let goodEntry = 0;
let wrongEntry = 0;
let combo = 0;

//words list
let words = [
  [
    //wave 1
    "l'espace",
    "est",
    "un",
    "vaste",
    "univers",
    "qui",
    "nous",
    "enchante",
    "par",
    "sa",
  ],
  [
    //wave 2
    "beauté",
    "et",
    "sa",
    "mystérieuse",
    "complexité",
    "l'étude",
    "de",
    "l'espace",
    "et",
    "des",
    "corps",
    "célestes",
    "qui",
    "le",
    "peuplent",
    "est",
    "une",
    "entreprise",
    "à",
    "la",
  ],
  [
    //wave 3
    "fois",
    "fascinante",
    "et",
    "impitoyable",
    "l'informatique",
    "est",
    "un",
    "outil",
    "puissant",
    "qui",
    "a",
    "revolutionné",
    "notre",
    "manière",
    "d'étudier",
    "l'univers",
    "et",
    "de",
    "comprendre",
    "ses",
    "mystères",
    "les",
    "algorithmes",
    "et",
    "les",
    "méthodes",
    "mathématiques",
    "développés",
    "par",
    "les",
    "informaticiens",
  ],
  [
    //wave 4
    "ont",
    "permis",
    "une",
    "analyse",
    "plus",
    "précise",
    "et",
    "efficace",
    "et",
    "offrent",
    "des",
    "données",
    "spatiales",
    "ce",
    "qui",
    "a",
    "abouti",
    "à",
    "de",
    "nouvelles",
    "découvertes",
    "et",
    "à",
    "une",
    "meilleure",
    "compréhension",
    "de",
    "l'univers",
    "ensemble",
    "espace",
    "et",
    "informatique",
    "offrent",
    "des",
    "possibilités",
    "infinies",
    "de",
    "découverte",
    "et",
    "de",
    "progrès",
  ],
  [
    //wave 5
    "les",
    "étoiles",
    "qui",
    "scintillent",
    "dans",
    "la",
    "nuit",
    "nous",
    "rappellent",
    "notre",
    "petitesse",
    "dans",
    "l'univers",
    "mais",
    "aussi",
    "notre",
    "importance",
    "en",
    "tant",
    "qu'observateurs",
    "et",
    "chercheurs",
    "l'astronomie",
    "nous",
    "permet",
    "d'explorer",
    "les",
    "limites",
    "de",
    "notre",
    "connaissance",
    "et",
    "de",
    "nous",
    "émerveiller",
    "face",
    "à",
    "la",
    "beauté",
    "du",
    "cosmos",
    "infinité",
    "et",
    "mystère",
    "sont",
    "au",
    "coeur",
    "de",
    "cette",
    "discipline",
  ],
  [
    //wave 6
    "les",
    "planètes",
    "et",
    "leurs",
    "lunes",
    "sont",
    "des",
    "mondes",
    "à",
    "eux",
    "seuls",
    "avec",
    "leurs",
    "propres",
    "histoires",
    "et",
    "leurs",
    "propres",
    "mystères",
    "l'étude",
    "des",
    "planètes",
    "et",
    "du",
    "système",
    "solaire",
    "nous",
    "permet",
    "de",
    "comprendre",
    "notre",
    "propre",
    "origine",
    "et",
    "notre",
    "place",
    "dans",
    "l'univers",
    "mais",
    "aussi",
    "d'imaginer",
    "de",
    "nouvelles",
    "formes",
    "de",
    "vie",
    "et",
    "d'explorer",
    "de",
    "nouveaux",
    "horizons",
  ],
  [
    //wave 7
    "le",
    "voyage",
    "dans",
    "l'espace",
    "a",
    "toujours",
    "fasciné",
    "l'humanité",
    "et",
    "nous",
    "avons",
    "réalisé",
    "des",
    "progrès",
    "considérables",
    "au",
    "cours",
    "des",
    "dernières",
    "décennies",
    "mais",
    "nous",
    "sommes",
    "encore",
    "loin",
    "d'explorer",
    "toutes",
    "les",
    "merveilles",
    "de",
    "l'espace",
    "les",
    "voyages",
    "spatiaux",
    "sont",
    "un",
    "défi",
    "technologique",
    "et",
    "humain",
    "sans",
    "précédent",
    "qui",
    "nous",
  ],
  [
    //wave 8
    "que",
    "ce",
    "soit",
    "pour",
    "explorer",
    "les",
    "confins",
    "de",
    "l'univers",
    "ou",
    "pour",
    "résoudre",
    "des",
    "problèmes",
    "complexes",
    "sur",
    "terre",
    "les",
    "technologies",
    "de",
    "l'espace",
    "et",
    "de",
    "l'informatique",
    "sont",
    "essentielles",
    "pour",
    "notre",
    "avenir",
    "en",
    "tant",
    "que",
    "civilisation",
    "avancée",
    "nous",
    "sommes",
    "chanceux",
    "de",
    "vivre",
    "à",
    "une",
    "époque",
    "où",
    "nous",
    "pouvons",
    "utiliser",
    "ces",
    "outils",
    "incroyables",
    "pour",
    "explorer",
    "et",
    "comprendre",
    "le",
    "monde",
  ],
  [
    //wave 9
    "qui",
    "nous",
    "entoure",
    "mais",
    "nous",
    "devons",
    "aussi",
    "reconnaître",
    "la",
    "responsabilité",
    "que",
    "nous",
    "avons",
    "de",
    "préserver",
    "ces",
    "merveilles",
    "pour",
    "les",
    "générations",
    "futures",
    "cela",
    "implique",
    "un",
    "engagement",
    "envers",
    "la",
    "durabilité",
    "et",
    "la",
    "protection",
    "de",
    "notre",
    "planète",
    "et",
    "de",
    "nos",
    "ressources",
    "naturelles",
    "nous",
    "devons",
    "travailler",
    "ensemble",
    "pour",
    "assurer",
    "un",
    "avenir",
    "meilleur",
    "pour",
    "tous",
    "et",
    "pour",
    "notre",
    "planète",
    "elle-même",
  ],
  [
    // wave 10
    "les",
    "avancées",
    "récentes",
    "en",
    "astrophysique",
    "ont",
    "révélé",
    "des",
    "phénomènes",
    "cosmiques",
    "étonnants",
    "tels",
    "que",
    "les",
    "trous",
    "noirs",
    "les",
    "ondes",
    "gravitationnelles",
    "et",
    "la",
    "matière",
    "noire",
    "ces",
    "découvertes",
    "ont",
    "ouvert",
    "de",
    "nouvelles",
    "perspectives",
    "dans",
    "la",
    "compréhension",
    "de",
    "l'univers",
    "mais",
    "ont",
    "aussi",
    "soulevé",
    "de",
    "nouvelles",
    "questions",
    "auxquelles",
    "les",
    "scientifiques",
    "tentent",
    "de",
    "répondre",
    "aujourd'hui",
    "et",
    "dans",
    "les",
    "années",
    "à",
    "venir",
  ],
  [
    // boss wave
    "mettre ici un texte long et une vitesse réduite pour que le bosse avance et le joueur doit saisir le texte entier pou détruire le boss une fois le paragraphe temrminé ca enléve le bouclier du boss il en a 3 et une fois les 3 boucliers détruits on peux tuer le boss",
  ],
];
