let wordList = [
    [
    "lespace",
    "est",

    ],
    [
    "lavie",
    "est",
    "un",,
 ], 
        [
        "lamour",
        "est",
        "un",
        "vaste",
        ]
    
];

// "l amour",
//     "est",
//     "un",
//     "vaste",
//     "univers",
//         // "qui",
        // "nous",
        // "enchante",
        // "par",
        // "sa",
        // "beauté",
        // "et",
        // "sa",
        // "mystérieuse",
        // "complexité",
        // "l'étude",
        // "de",
        // "l'espace",
        // "et",
        // "des",
        // "corps",
        // "célestes",
        // "qui",
        // "le",
        // "peuplent",
        // "est",
        // "une",
        // "entreprise",
        // "à",
        // "la",
        // "fois",
        // "fascinante",
        // "et",
        // "impitoyable",
        // "l'informatique",
        // "est",
        // "un",
        // "outil",
        // "puissant",
        // "qui",
        // "a",
        // "revolutionné",
        // "notre",
        // "manière",
        // "d'étudier",
        // "l'univers",
        // "et",
        // "de",
        // "comprendre",
        // "ses",
        // "mystères",
        // "les",
        // "algorithmes",
        // "et",
        // "les",
        // "méthodes",
        // "mathématiques",
        // "développés",
        // "par",
        // "les",
        // "informaticiens",
        // "ont",
        // "permis",
        // "une",
        // "analyse",
        // "plus",
        // "précise",
        // "et",
        // "efficace",
        // "des",
        // "données",
        // "spatiales",
        // "ce",
        // "qui",
        // "a",
        // "abouti",
        // "à",
        // "de",
        // "nouvelles",
        // "découvertes",
        // "et",
        // "à",
        // "une",
        // "meilleure",
        // "compréhension",
        // "de",
        // "l'univers",
        // "ensemble",
        // "espace",
        // "et",
        // "informatique",
        // "offrent",
        // "des",
        // "possibilités",
        // "infinies",
        // "de",
        // "découverte",
        // "et",
        // "de",
        // "progrès",